version: "3.9"

services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    env_file:
      - docker.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    restart: unless-stopped
    networks:
      ch_net:
        ipv4_address: 172.89.0.2
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - 5000:5000
    env_file:
      - docker.env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      ch_net:
        ipv4_address: 172.89.0.3
    command: ["./wait-for-postgres.sh", "db", "npm", "run", "start:prod"]

networks:
  ch_net:
    ipam:
      config:
        - subnet: 172.89.0.0/16

volumes:
  postgres-data:
